name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build:gh

      - name: Prepare deploy action
        run: |
          npm install
          npm run build
        working-directory: .github/actions/github-pages-deploy-action

      - name: Deploy 🚀
        uses: ./.github/actions/github-pages-deploy-action
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist
          single-commit: true
          clean: true
